name = "blockhaven"
compatibility_date = "2026-06-28"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "blockhaven_db"
database_id = "replace-with-your-cloudflare-d1-database-id"
